### ISSUE TITLE
POST create needs work

### ISSUE THREAD

**Issue by wadewilliams** [gundotio/worf#50]
Create hypothetically works, but it's untested, and in certain situations, we should allow a way to return the instance instead of the response, such that you can perform further custom actions on the new instance before returning response.

**Comment by stevelacey** [comment]
This still need work, but you can now grab the instance via overriding the `create` hook added in #54.

**Comment by stevelacey** [comment]
This is most of the way there at this point, `create` supports everything `update` does... except validation isn't quite the same, once we've audited guild we can flip the switch on that.

**Comment by stevelacey** [comment]
Further work can have new issues, creates are now validated and have basically all of the functionality of updates.
