### ISSUE TITLE
Add PUT support to DetailUpdateAPI

### ISSUE THREAD

**Issue by stevelacey** [gundotio/worf#7]
I mean, I guess it should support it, right? It only supports PATCH currently, I was trying to PUT for 5 minutes before I checked the worf source to work out why I was getting a 405... yay for the 405's working though 🎉️

**Comment by wadewilliams** [comment]
We can add put along side patch, I've read the spec a few times and still cannot reliably remember what the difference is. I suppose PUT is not supposed to do a partial update, it's a full replace? So PATCH should allow a sub-set of attributes to be updated, where PUT would technically require all of them? Does that sound right?

**Comment by stevelacey** [comment]
Yes

**Comment by stevelacey** [comment]
I added support, it does the same things as `PATCH`, you'd probably want to use a serializer that makes all fields as `required=True`, which is a concept marshmallow supports.
