### ISSUE TITLE
Browsable API Template Does Not Exist

### ISSUE THREAD

**Issue by wadewilliams** [gundotio/worf#83]
https://github.com/gundotio/worf/blob/master/worf/views/base.py#L58-L59

The template file isn't registered appropriately, so this only works if you are running a development environment with a copy of `worf` available, instead of via package install

As a side note it'd probably be worth allowing for users to configure a setting for this, either using `debug` or a more specific variable.

**Comment by stevelacey** [comment]
@wadewilliams is `worf` in your `INSTALLED_APPS`? That should be the only requirement. This is tested. Setting added in https://github.com/gundotio/worf/pull/84.

**Comment by stevelacey** [comment]
Resolved in https://github.com/gundotio/worf/commit/4d6f22e3b56cc94e12ce7ed343a7217934e0ef85
